<?php
/* @var $this PrescriptionController */
/* @var $model Prescription */
?>

<style>
    body {
        font-family: "Nunito", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif !important;
        color: #000 !important;
    }
    .text-primary { color: #02700d !important; }
</style>

<div class="container mt-4">

    <div class="row mb-4 border-bottom pb-3 align-items-center">
        <div class="col-2 text-center">
             <img src="<?php echo Yii::app()->request->baseUrl; ?>/img/logo.png" style="width: 80px; height: 80px; object-fit: contain;">
        </div>
        <div class="col-8 text-center">
            <h2 class="font-weight-bold mb-0 text-uppercase" style="color: #02700d;">Quali-Life Health Center</h2>
            <p class="mb-0 text-gray-600">11930, Ubas St, Mabalacat City, Pampanga</p>
            <p class="small text-gray-600">Digital Medical Prescription</p>
        </div>
        <div class="col-2 text-right">
             <div class="font-weight-bold text-gray-800" style="font-size: 1.2rem;">RX #: <?php echo $model->id; ?></div>
             <div class="text-gray-600"><?php echo date('M j, Y', strtotime($model->date_of_prescription)); ?></div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-6">
            <div class="p-3 border rounded" style="background-color: #f8f9fa;">
                <h6 class="text-uppercase text-secondary font-weight-bold mb-2 small" style="color: #d0be02 !important;">Patient Details</h6>
                <h4 class="font-weight-bold text-dark mb-1">
                    <?php 
                    if(isset($model->patientAccount->user)) {
                        echo CHtml::encode($model->patientAccount->user->firstname . ' ' . $model->patientAccount->user->lastname);
                    } else {
                        echo "Unknown Patient";
                    }
                    ?>
                </h4>
                <p class="mb-0 text-dark">
                    ID: <strong><?php echo $model->patient_account_id; ?></strong>
                </p>
                <?php if(isset($model->patientAccount->user)): ?>
                <p class="mb-0 text-dark small">
                    Age: <?php echo date_diff(date_create($model->patientAccount->user->dob), date_create('today'))->y; ?> | 
                    Gender: <?php echo ($model->patientAccount->user->gender == 1 ? 'Male' : 'Female'); ?>
                </p>
                <?php endif; ?>
            </div>
        </div>

        <div class="col-6">
            <div class="p-3 border rounded" style="background-color: #f8f9fa;">
                <h6 class="text-uppercase text-secondary font-weight-bold mb-2 small" style="color: #d0be02 !important;">Prescribing Doctor</h6>
                <h4 class="font-weight-bold text-primary mb-1">
                    <?php 
                    if(isset($model->doctorAccount->user)) {
                        echo "Dr. " . CHtml::encode($model->doctorAccount->user->firstname . ' ' . $model->doctorAccount->user->lastname);
                    } else {
                        echo "Unknown Doctor";
                    }
                    ?>
                </h4>
                <p class="mb-0 text-dark">
                    General Physician
                </p>
                <p class="mb-0 text-dark small">
                    License #: 12345-678
                </p>
            </div>
        </div>
    </div>

    <div class="text-left mb-2 pl-3">
        <i class="fas fa-prescription fa-2x text-secondary" style="color: #ccc;"></i>
    </div>

    <div class="border rounded p-4 mb-5" style="min-height: 300px; font-size: 14pt; line-height: 1.6; border-color: #000 !important;">
        <?php 
            echo nl2br(CHtml::encode($model->prescription)); 
        ?>
    </div>

    <div class="row mt-5 pt-5">
        <div class="col-8">
            <p class="small text-muted mb-0">
                <strong>Disclaimer:</strong> This is a computer-generated prescription. Valid without physical signature if verified by the system.
            </p>
            <p class="small text-muted">
                Generated by Quali-Life System on <?php echo date('Y-m-d H:i:s'); ?>
            </p>
        </div>
        <div class="col-4 text-center">
            <div class="border-bottom mb-2" style="border-bottom: 2px solid #000 !important; width: 90%; margin: 0 auto;">
                <img src="<?php echo Yii::app()->request->baseUrl; ?>/img/signature_placeholder.png" onerror="this.style.display='none'" style="height: 50px; opacity: 0.8;">
            </div>
            <div class="font-weight-bold text-uppercase">Doctor's Signature</div>
        </div>
    </div>

</div>